# Generated by Django 4.0.6 on 2022-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storekeeper', '0002_warehouse_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='actual',
            field=models.IntegerField(default=1, verbose_name='Фактическое количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='article',
            field=models.CharField(default=1, max_length=200, verbose_name='Артикул товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='characteristic',
            field=models.CharField(default=1, max_length=150, verbose_name='Характеристика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='client',
            field=models.CharField(default=1, max_length=150, verbose_name='Наименование заказчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='dateArrival',
            field=models.DateField(auto_now_add=True, db_index=True, default="2022-10-20", verbose_name='Дата прихода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='dateCompilation',
            field=models.DateField(db_index=True, default="2022-10-20", verbose_name='Дата составления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='documentNumber',
            field=models.CharField(default=1, max_length=200, verbose_name='Номер документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(default=1, upload_to='media/images/%Y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='priceNDS',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Сумма без НДС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sort',
            field=models.CharField(default=1, max_length=150, verbose_name='Сорт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='unit',
            field=models.CharField(default=1, max_length=200, verbose_name='Наименование еденицы измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование товара'),
        ),
    ]
