# Generated by Django 4.0.6 on 2022-10-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storekeeper', '0004_alter_warehouse_actual_alter_warehouse_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='xlsfile',
            field=models.FileField(null=True, upload_to='media/xls'),
        ),
    ]
