# Generated by Django 4.0.6 on 2022-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storekeeper', '0005_warehouse_xlsfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsfile', models.FileField(null=True, upload_to='media/xls/%Y/%m/%d/', verbose_name='Файл')),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='xlsfile',
        ),
    ]
