# Generated by Django 4.0.6 on 2022-10-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storekeeper', '0006_upfile_remove_warehouse_xlsfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upfile',
            options={'verbose_name': 'Загрузка файла', 'verbose_name_plural': 'Загрузка файла'},
        ),
    ]
