# Generated by Django 4.0.6 on 2022-08-16 06:14

from django.contrib.auth.models import Group
from django.db import migrations


def add_groups(apps, schema_editor):
    list_groups = ['Технолог', 'Швея', 'Раскройщик', 'Бухгалтер', 'Кладовщик']
    for group in list_groups:
        group_model = Group(name=group)
        group_model.save()


def remove_groups(apps, schema_editor):
    list_groups = ['Технолог', 'Швея', 'Раскройщик', 'Бухгалтер', 'Кладовщик']
    for group in list_groups:
        Group.objects.filter(name=group).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups, remove_groups)
    ]
