# Generated by Django 4.0.6 on 2022-08-16 06:24

from django.db import migrations





class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0002_auto_20220816_1114'),
    ]

    operations = [
    ]
