# Generated by Django 4.0.6 on 2022-10-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofwork',
            options={'verbose_name': 'Вид работы', 'verbose_name_plural': 'Вид работы'},
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость выполнения (в секундах)'),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Вид работы'),
        ),
    ]
