# Generated by Django 4.0.6 on 2022-10-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Зарплата', 'verbose_name_plural': 'Зарплата'},
        ),
    ]
