# Generated by Django 4.0.6 on 2022-08-16 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seamstress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factofexecution',
            options={'verbose_name': 'Факт выполнения', 'verbose_name_plural': 'Факт выполнения'},
        ),
        migrations.AddField(
            model_name='factofexecution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factofexecution',
            name='completed',
            field=models.IntegerField(verbose_name='Выполненный факт'),
        ),
        migrations.AlterField(
            model_name='factofexecution',
            name='spent',
            field=models.IntegerField(verbose_name='Затраченно времени'),
        ),
    ]
