# Generated by Django 4.0.6 on 2022-08-16 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seamstress', '0002_alter_factofexecution_options_factofexecution_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factofexecution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
