# Generated by Django 4.0.6 on 2022-10-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seamstress', '0003_alter_factofexecution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='factofexecution',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Зарплата'),
            preserve_default=False,
        ),
    ]
