# Generated by Django 4.0.6 on 2022-10-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seamstress', '0004_factofexecution_wages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='Часы работы')),
            ],
        ),
    ]
