# Generated by Django 4.0.6 on 2022-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_products', models.CharField(db_index=True, max_length=150, verbose_name='Вид продукции')),
                ('type_work', models.CharField(choices=[('Сл', 'Сложная'), ('Ср', 'Средняя'), ('Ле', 'Легкая')], max_length=20, verbose_name='Вид работы')),
                ('quantity', models.IntegerField(verbose_name='Необходимое количество')),
            ],
        ),
    ]
