# Generated by Django 4.0.6 on 2022-08-15 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technologist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'verbose_name': 'Вид продукции', 'verbose_name_plural': 'Вид продукции'},
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
