# Generated by Django 4.0.6 on 2022-08-24 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technologist', '0002_alter_typeproduct_options_typeproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('time', models.IntegerField(verbose_name='Время в секундах')),
                ('spent', models.IntegerField(verbose_name='Стоймость')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Операция', to='technologist.operation', verbose_name='Операция')),
                ('seamstress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Швея')),
                ('tec_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologist.technicalprocess')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Время', to='technologist.operation', verbose_name='Время в секундах')),
            ],
        ),
    ]
