# Generated by Django 4.0.6 on 2022-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologist', '0003_operation_technicalprocess_selectionoperation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операция'},
        ),
        migrations.AlterModelOptions(
            name='selectionoperation',
            options={'verbose_name': 'Выбор операции', 'verbose_name_plural': 'Выбор операции'},
        ),
        migrations.AlterModelOptions(
            name='technicalprocess',
            options={'verbose_name': 'Технический процесс', 'verbose_name_plural': 'Технический процесс'},
        ),
        migrations.AlterField(
            model_name='selectionoperation',
            name='time',
            field=models.IntegerField(verbose_name='Время в секундах'),
        ),
    ]
