# Generated by Django 4.0.6 on 2022-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologist', '0005_alter_typeproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('waste', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Нормы расхода')),
                ('unit', models.CharField(max_length=255, verbose_name='Ед. изм.')),
                ('total', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Итого')),
            ],
            options={
                'verbose_name': 'Нормы расхода',
                'verbose_name_plural': 'Нормы расхода',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование изделия')),
                ('body', models.CharField(max_length=255, verbose_name='Размер / рост')),
                ('quantity', models.IntegerField(verbose_name='Количество (комплектов, пар, штук)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена изготовления одной ед. продукции, руб.')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость изготовления продукции, руб.')),
                ('totalQ', models.IntegerField(verbose_name='Итого: Количество (комплектов, пар, штук)')),
                ('totalC', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итого: Стоимость изготовления продукции, руб.')),
            ],
            options={
                'verbose_name': 'Изделия',
                'verbose_name_plural': 'Изделия',
            },
        ),
    ]
