# Generated by Django 4.0.6 on 2022-10-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologist', '0006_expenses_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='body',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalQ',
        ),
        migrations.AddField(
            model_name='expenses',
            name='order_expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologist.order'),
        ),
        migrations.CreateModel(
            name='OrderAny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255, verbose_name='Размер / рост')),
                ('quantity', models.IntegerField(verbose_name='Количество (комплектов, пар, штук)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена изготовления одной ед. продукции, руб.')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость изготовления продукции, руб.')),
                ('totalQ', models.IntegerField(verbose_name='Итого: Количество (комплектов, пар, штук)')),
                ('totalC', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итого: Стоимость изготовления продукции, руб.')),
                ('order_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologist.order')),
            ],
        ),
    ]
