# Generated by Django 4.0.6 on 2022-10-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologist', '0007_remove_order_body_remove_order_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderany',
            options={'verbose_name': 'Изделия', 'verbose_name_plural': 'Изделия'},
        ),
    ]
