# Generated by Django 4.0.6 on 2022-10-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seamstress', '0005_hours'),
        ('technologist', '0009_alter_typeproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='hour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seamstress.hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='period',
            field=models.IntegerField(default=1, verbose_name='Срок выполнения (в часах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='time',
            field=models.IntegerField(default=1, verbose_name='Срок выполнения'),
            preserve_default=False,
        ),
    ]
