# Generated by Django 4.0.6 on 2022-10-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seamstress', '0005_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technologist', '0010_typeproduct_hour_typeproduct_period_typeproduct_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.CharField(max_length=150, verbose_name='Загруженность цеха')),
            ],
            options={
                'verbose_name': 'Загруженность цеха',
                'verbose_name_plural': 'Загруженность цеха',
            },
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seamstress.hours'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Швеи'),
        ),
    ]
