# Generated by Django 4.0.6 on 2022-10-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technologist', '0011_workload_alter_typeproduct_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='ser',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения(в секундах)'),
        ),
    ]
