# Generated by Django 4.0.6 on 2022-10-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologist', '0012_workload_ser_alter_typeproduct_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'verbose_name': 'План швеи', 'verbose_name_plural': 'План швеи'},
        ),
    ]
