# Generated by Django 4.0.6 on 2022-08-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('number', models.CharField(db_index=True, max_length=100)),
                ('appellation', models.CharField(db_index=True, max_length=150)),
                ('metric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('flooring', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remains', models.IntegerField(db_index=True)),
                ('defects', models.IntegerField()),
                ('quantity', models.IntegerField(db_index=True)),
                ('spent', models.TimeField()),
            ],
        ),
    ]
