# Generated by Django 4.0.6 on 2022-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0003_alter_dailyproductionplan_appellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workperformed',
            name='image',
            field=models.ImageField(upload_to='media/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
