# Generated by Django 4.0.6 on 2022-08-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0004_alter_workperformed_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyproductionplan',
            options={'verbose_name': 'Ежедневный план выпуска продукции', 'verbose_name_plural': 'Ежедневный план выпуска продукций'},
        ),
        migrations.AlterModelOptions(
            name='typematerials',
            options={'verbose_name': 'Вид сырья', 'verbose_name_plural': 'Вид сырья'},
        ),
        migrations.AlterModelOptions(
            name='workperformed',
            options={'verbose_name': 'Выполненная работа', 'verbose_name_plural': 'Выполненая работа'},
        ),
    ]
