# Generated by Django 4.0.6 on 2022-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0005_alter_dailyproductionplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workperformed',
            name='image',
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='image',
            field=models.ImageField(default=1, upload_to='media/images/%Y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
