# Generated by Django 4.0.6 on 2022-08-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0006_remove_workperformed_image_dailyproductionplan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproductionplan',
            name='appellation',
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='visible_defects',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=15, verbose_name='Видимый брак'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='сloth',
            field=models.CharField(db_index=True, default=1, max_length=150, verbose_name='Ткань'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='defects',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15, verbose_name='Перекрой брака'),
        ),
    ]
