# Generated by Django 4.0.6 on 2022-08-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0007_remove_dailyproductionplan_appellation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyproductionplan',
            old_name='сloth',
            new_name='cloth',
        ),
    ]
