# Generated by Django 4.0.6 on 2022-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0008_rename_сloth_dailyproductionplan_cloth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='defects',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Перекрой брака'),
        ),
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='visible_defects',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Видимый брак'),
        ),
    ]
