# Generated by Django 4.0.6 on 2022-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0009_order_alter_dailyproductionplan_defects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='typematerials',
            name='feedstock',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Вид сырья'),
        ),
    ]
