# Generated by Django 4.0.6 on 2022-10-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0010_alter_dailyproductionplan_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование операции')),
                ('time', models.IntegerField(verbose_name='Время в секундах')),
            ],
            options={
                'verbose_name': 'Технические операции',
                'verbose_name_plural': 'Технические операции',
            },
        ),
        migrations.RemoveField(
            model_name='workperformed',
            name='materials',
        ),
        migrations.DeleteModel(
            name='TypeMaterials',
        ),
    ]
