# Generated by Django 4.0.6 on 2022-10-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0011_tecoperation_remove_workperformed_materials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedstock', models.CharField(db_index=True, max_length=150, verbose_name='Вид сырья')),
            ],
            options={
                'verbose_name': 'Вид сырья',
                'verbose_name_plural': 'Вид сырья',
            },
        ),
        migrations.RemoveField(
            model_name='dailyproductionplan',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='dailyproductionplan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dailyproductionplan',
            name='visible_defects',
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=150, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workperformed',
            name='image',
            field=models.ImageField(default=1, upload_to='media/images/%Y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='defects',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Брак'),
        ),
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='spent',
            field=models.IntegerField(verbose_name='Затрачено времени (в секундах)'),
        ),
        migrations.AlterField(
            model_name='workperformed',
            name='spent',
            field=models.IntegerField(verbose_name='Затрачено времени (в секундах)'),
        ),
        migrations.AddField(
            model_name='workperformed',
            name='materials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='cutter.typematerials', verbose_name='Вид сырья'),
            preserve_default=False,
        ),
    ]
