# Generated by Django 4.0.6 on 2022-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0012_typematerials_remove_dailyproductionplan_cloth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPerformedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Б', 'Большая'), ('С', 'Средняя'), ('М', 'Мелкая')], max_length=20, verbose_name='Размер детали')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Стоимость детали',
                'verbose_name_plural': 'Стоимость детали',
            },
        ),
        migrations.AlterField(
            model_name='workperformed',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
