# Generated by Django 4.0.6 on 2022-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0013_workperformedcost_alter_workperformed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='choice',
            field=models.CharField(blank=True, choices=[('Л', 'Лекал'), ('Р', 'Раскладка')], max_length=25, verbose_name='Лекал/Раскладок'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, verbose_name='Достаточность поступившего материала'),
        ),
        migrations.AddField(
            model_name='order',
            name='made',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Срок выполнения раскроя'),
        ),
    ]
